### ISSUE TITLE
Вёрстка страницы с сообщениями

### ISSUE THREAD

**Issue by KirMoro** [KirMoro/slackonarus#2]
- [x] Карточка сообщения, которая меняет ширину в зависимости от степени вложенности
- [x] Отображение аватара и текста. Эмодзи и вложения пока не учитываем
- [x] Название слаконара и автор
- [x] Сделать красиво

**Comment by Melodyn** [comment]
Привет! Хорошая работа, позади шаг "самое сложное - это начать". Версия ещё не для прода, но дальше её можно просто улучшать. Что сделать опишу ниже.

## Вёрстка

### Общая

Сейчас страница с сообщениями не по центру экрана :) Переведи её тоже на бутстрап и не забудь дропнуть нормалайз, т.к. бутстрап уже его использует под капотом. Если быть точным, то у них собственный [Reboot](https://getbootstrap.com/docs/5.2/content/reboot/). Я думаю, что кастомные стили почти никогда не понадобятся, разве что точечно.

Для инпутов формы не хватает атрибута `name`, а самой форме атрибута `action`. Если их добавить, то тогда после отправки формы нас будет перекидывать на страницу слаконара, а урл будет примерно такой:
```
/chatlist.html?title=Hello World&author=Kirill Morozov&first=https://hexlet-students.slack.com/archives/C03L9DBH708/p1660057772213509&last=https://hexlet-students.slack.com/archives/C03L9DBH708/p1660142789914989
```

Этой ссылкой можно будет поделиться с кем-то ещё, чтобы он тоже открыл слаконар и почитал прямо из веб-версии.

### Сообщения

Вложенные сообщения можно сверстать на вложенных списках, тогда не понадобятся отдельные стили для сообщений верхнего и нижнего уровней. Вот такой код:
```html
<ul>
  <li>Hello</li>
  <li>
    <ul>
      <li>World</li>
      <li>Kitty</li>
    </ul>
  </li>
  <li>
    Goodbye doge
  </li>
  <li>
    What
    <ul>
      <li>is</li>
      <ul>
        <li>love</li>
      </ul>
    </ul>
  </li>
</ul>
```
Превратится в такую структуру:
<ul>
  <li>Hello</li>
  <li>
    <ul>
      <li>World</li>
      <li>Kitty</li>
    </ul>
  </li>
  <li>
    Goodbye doge
  </li>
  <li>
    What
    <ul>
      <li>is</li>
      <ul>
        <li>love</li>
      </ul>
    </ul>
  </li>
</ul>

Вместо кастомной вёрстки попробуй использовать бутстрап. Для вдохновения можно погуглить "chat message card on bootstrap 5". Я например нашёл тут: https://mdbootstrap.com/docs/standard/extended/chat/ симпатичное решение, как мне кажется:

![Image](https://user-images.githubusercontent.com/26752238/190845114-df095c3b-cefd-46e4-a727-dc44f3bb79ac.png)

Там ниже есть версия с градиентами. Если сверстаем эту версию сначала простой, то потом можно тоже добавить стилизацию бэкграундами и прозрачностью.

## Код

### Класс SlackAPI/ FakeSlackAPI

Когда мы начнём писать класс API, он будет в конструктор принимать конфиг используемой апишки и содержать несколько методов. Давай опишем интерфейсы:

Конфиг API:
```js
{
  url: 'https://slack.com/api', // куда стучаться за данными
  token: 'some-slack-token', // с каким токеном стучаться
}
```

Поскольку у нас ограниченная функциональность и есть конкретная задача скачивания сообщений от ссылки `А` до ссылки `Б`, то логично сделать в классе метод установки ссылок на сообщения. А получать из апи мы будем сообщения, реплаи и пользователей. Тогда в классе будут следующие методы:
```js
// устанавливает диапазон сообщений с которыми мы будем работать
setConversationRange({
  firstMessageURL: 'https://hexlet-students.slack.com/archives/C03L9DBH708/p1660057772213509',
  lastMessageURL: 'https://hexlet-students.slack.com/archives/C03L9DBH708/p1660142789914989',
})
// под капотом "парсит" ссылки, разбивая их на channel, oldest, latest и получится:
//   channel=C03L9DBH708
//   oldest=1660057772.213509
//   latest=1660142789.914989

// GET /conversations.history получаем все сообщения
getAllConversations()
// Обрати внимание на флаг has_more и подумай о рекурсии

// GET /conversations.replies получаем все треды
getAllReplies(conversationTS)
// conversationTS - значение поля "ts" из массива "messages", который пришёл из getAllConversations()

// GET /users.profile.get получаем пользователя
getAllReplies(userID)
// userID - значение поля "user" из массива "messages", который пришёл из getAllConversations() или getAllReplies
```

При этом надо где-то заложить мемоизацию. Если мы уже получали пользователя или сообщение, то чтобы за ним повторно не выполнялся запрос. Сделать это можно или в классе API, или до вызова его методов. Второй вариант предпочтительнее.

Соответственно, класс фейкового апи не может в конструктор принимать сообщения, пользователей и аватарки. Он должен полностью соответствовать реальному классу апи, но просто возвращать заранее подготовленные данные, самостоятельно их сортировать или даже генерировать (например через faker).

### Запуск приложения

У приложения есть период загрузки, инициализации и, собственно, работы. До того, как приложение загрузилось, лучше чтобы JS-код не выполнялся. Для этого есть событие "DOMContentLoaded":
```js
const run = async (config, slackApi) => {
  // some black magic here
};

// Навешиваем обработчик, который выполнится только после полной загрузки DOM
document.addEventListener('DOMContentLoaded', () => {
  // isProductionMode, configSlackApi, selectors - это типа уже существующие где-то переменные/константы
  const ApiService = isProductionMode ? SlackAPI : FakeAPI;
  const slackApi = new ApiService(configSlackApi);
  // дальше парсинг url страницы и вызов slackApi.setConversationRange

  run(selectors, slackApi)
    .catch((err) => { // единый обработчик ошибок на верхнем уровне
      console.error(err);
      alert(err.message);
    });
});
```

----

Несмотря на объёмность ревью, на самом деле всё делается достаточно быстро. Если будут вопросы, как обычно, пиши в общий чат, прикладывай ссылки, будем обсуждать.

**Comment by Melodyn** [comment]
# Ревью 2

В этот раз ты получил бесценный опыт оверинжиниринга и теперь получишь бесценый опыт рефакторинга :) Поскольку разъехалась вёрстка, не рендярятся реплаи и код требует упрощения, сегодня чисто по технике.

## Класс апи

Поскольку кода стало много, уже можно абстрагировать немного модули. Класс апишки можно вынести в отдельный файл. В нём стоит учесть, что поскольку он эмулирует настоящее апи, то методы запроса в нём будут асинхронные. Лучше это сразу заложить, чтобы потом не переписывать код ещё раз.

Метод `setConversationRange` в классе апишки можно улучшить, если поменять регулярку и добавив проверку на число:
```javascript
  setConversationRange({ firstMessageURL, lastMessageURL }) {
    const firstURL = new URL(firstMessageURL);
    const lastURL = new URL(lastMessageURL);

    const [, , channel, oldestString] = firstURL.pathname.split('/');
    const [, , , latestString] = lastURL.pathname.split('/');
    // Получаем регуляркой все числа в конце строки. Может вернуться или массив или null, поэтому есть ИЛИ.
    const [parsedOldestString] = oldestString.match(/\d+$/) || [''];
    const [parsedLatestString] = latestString.match(/\d+$/) || [''];
    // Превращаем строки в числа (моет превратиться в NaN)
    const oldestNs = parseFloat(parsedOldestString);
    const latestNs = parseFloat(parsedLatestString);

    if (isNaN(oldestNs) || isNaN(latestNs) || !channel) {
      // Пусть кто-то снаружи узнает, что что-то не так. Можно возвращать объект ошибки
      return false;
    }

    const oldest = oldestNs / nanoSecondsInMilliseconds;
    const latest = oldestNs / nanoSecondsInMilliseconds;

    // бывший this._range
    this.conversation = {
      channel,
      oldest,
      latest,
    };

    return true;
  }
```
В конструкторе класса лучше задавать все свойства класса заранее. То, как сейчас задан `this._range` может привести к тому, что код, который его использует почему-то будет вызван раньше, чем он установится и тогда мы упадём с ошибкой кода. Паттерн Null Object - твой бро, придерживайся его.

Конфиг: https://github.com/KirMoro/slackonarus/blob/main/index.js#L4-L11 надо поправить так, чтобы там был только apiURL и token, а части путей не являются частью конфига, как правило.

## Основная функция приложения

Функции, типа `run` обычно получают в себя либо `process.env`, либо любую другую переменную с глобальным конфигом всего приложения. Но не массивы сообщений или любые данные. Поэтому рассматривай её пока как функцию, которая один раз запускается с верхнего уровня и использует у себя по капотом всё необходимое. Многие константы лучше объявлять прямо в ней, чтобы при перезапуске приложения они гарантированно сбрасывались.

## Эксплуатация класса в основной функции

Поскольку получения всех сообщений, всех реплаев и всех пользователей - это 3 этапа, то они решаются в условные 3 строки. Особо сообщения и реплаи можно не увязывать, так как для них есть общее свойство thread_ts, поэтому можно получить три плоских массива. Чтобы было интереснее написать самому, код который мы обсуждали прикрепляю скрином:
![Image](https://user-images.githubusercontent.com/26752238/194927727-2de4aeff-2c71-4794-9c7d-43a57d5dda64.png)

**Comment by Melodyn** [comment]
# Ревью 3

Очень хорошо, надеюсь, что при переписывании кода ты преисполнился :) В этом ревью я решил вернуться от кода к вёрстке, поработаем над причёсыванием страницы.

## Про классы бутстрапа

Я так вижу, что в примере, который мы с тобой взяли как отправную точку почему-то отличаются классы от того, что есть реально в бутстрапе. Поэтому я предлагаю тебе их перепроверить и заменить на аналогичные. Например, класса `shadow-1-strong` нет, а `shadow-sm` есть.

Кроме того, можно сделать всё немного компактнее. Я решил поверстать с утра и вот что у меня получилось:
![image](https://user-images.githubusercontent.com/26752238/195973309-ef2b37bb-9864-4a19-923d-d6a0f515959a.png)

## Про вложенные списки

В HTML для двух сообщения с ответами получилась такая структура: `ul>li+(ul>li)+li+(ul>li))`, хотя если ты посмотришь примеры из первого ревью, должна была получиться такая: `ul>li+(li>(ul>li))+li+(li>(ul>li)))`. То есть внутри `ul` всегда лежат только `li`. А вот внутри `li` уже может лежать любой контент, даже другой `ul`. За счёт этого и работает магия с отступами слева.

В нашем случае есть развилка того как организовать вложенность. Если мы делаем как я написал, то из-за аватарок придётся задавать большой отступ слева для вложенных `ul`. Это вполне себе рабочий способ, хотя мы не можем гарантировать, что отступ слева будет точно равен аватарке и её отступу. Точнее, можем, но только кастомными стилями, чего не хотелось бы.

Второй вариант - это делать вложенный список под карточкой (`.card`). Тогда у нас гарантированно вложенный список находится на одном уровне, но надо занулять ненужные отступы и добавлять div-обёртку. При этом мы сохраняем семантику, так как `ul` вложен в `li`, а не в `ul`.

Я самостоятельно попробовал реализовать оба способа и они оба мне дались достаточно просто, с использованием только классов бутстрапа. Поэтому думаю, что могу оставить тебе на выбор реализацию.

## Про кастомные классы и центрирование контента

Удали собственный CSS и практикуйся с работой на чистом бутстрапе. Пока у нас нет таких задач, которые требовали бы кастомизации. Посмотри `container` в бутстрапе для выравнивания контента в центре и примени его к body. 

Одна особенность связана с цветами. Если задать `.bg-light` для body, то списки останутся белыми. Для исправления этого надо добавить `.bg-transparent` каждому `li`. Хз почему так, но как есть.

----

Со стороны может показаться, что работы требуется не так много, но на самом деле тут можно засесть на целый вечер. Если нужна помощь - пиши, созвонимся и покодим.

**Comment by Melodyn** [comment]
# Ревью 4

Молодцом! По части вёрстки этой страницы остались места для улучшения, но их можно сделать по ходу работы. Поэтому предлагаю сделать в рамках этого ревью сразу несколько шагов по рефакторингу проекта прежде, чем выйти на новый уровень функциональности.

Итак, что мы можем однозначно улучшить:
1. Убрать CSS-файлы, классы не из бутстрапа в HTML и JS. Это касается не только страницы с сообщениям, но и ранее созданной формы, чтобы два раза не вставать.
2. Проверить свой проект линтером и исправить 796 найденных проблем. Бог в помощь!
3. Файл slackData можно положить в каталог с именем `__fixtures__` и добавить его в игнор линтера. Такое именование каталога идёт из фреймворка Jest, который используется для тестирования приложения. Обычно тесты лежать в каталоге `__tests__`, а данные для тестов в каталоге фикстур.
4. Вместо ручной обработки даты установить библиотеку [luxon](https://moment.github.io/luxon/#/?id=luxon), раскурить тему форматирования дат и решить задачу с датами красиво.

В целом, фронтендеру нужно быть дотошным для мелочей и тут есть определённое поле для улучшения. Дело в том, что первое сообщение из фикстуры содержит список, а рендерится всё сплошным абзацем. Его можно превратить в текст, похожий на исходный тремя способами:
1. Самый правильный и долгий. Рендерить текст из свойства `blocks`, а не из `text`. Там для каждой строки указан какой это тип сообщения, от чего можно понять как правильно рендерить сообщение. Когда-нибудь в светлом будущем может быть мы это реализуем, но не сегодня.
2. К тексту из свойства `text` применить метод `trim()`, чтобы обрезать отступы в начале и конце, а текст разбить по переносу строки и отрендерить каждый абзац в теге `p`. Кажется, что это решение не должно быть проблемным. Если посмотришь мою вёрстку, то я так и сделал.
3. К тексту из свойства `text` применить метод `trim()`, а к HTML-элементы с текстом добавить кастомный CSS-стиль  `white-space: pre-wrap;`. Тогда все отступы будут как в оригинале. Но в бутстрапе подходящего класса нет, это будет кастом, поэтому вариант не совсем наш бро.

Я предлагаю сделать этим рефакторингом мощный удар и дальше уже перейти непосредственно на работу со Slack API и отвлекаться на вёрстку только по мелочам.

**Comment by Melodyn** [comment]
Кажется, по этому ревью всё сделано. Отмечу только странное решение задачи с подключением luxon. Ты его добавил как npm-библиотеку и почему-то ещё вынес в отдельный файл, который подключал так:
```javascript
import { luxon } from './luxon.js';

const DateTime = luxon.DateTime;
```
Хотя можно было обойтись без файла и просто импортировать нужный объект:
```javascript
import { DateTime } from 'luxon';
```
Можно этот момент поправить и будет совсем хорошо. Ишью закрываю авансом.

ТЗ на новую функциональность составим отдельной таской.
